### PR TITLE
PKG-4687

### PR DESCRIPTION
**Pull request by cbouss**
https://github.com/jupyter-server/pytest-jupyter/tree/v0.10.1
https://anaconda.atlassian.net/browse/PKG-4687

Depends on https://github.com/AnacondaRecipes/jupyter_core-feedstock/pull/19

### CODE REVIEW

**Review by JamesRobertsonGames — APPROVED** [review]

**Review by ifitchet — COMMENTED** [review]
`pyproject.toml` says these are optional dependencies.  Should they be in `run_constrained`?

**Comment by cbouss** [comment]
> `pyproject.toml` says these are optional dependencies. Should they be in `run_constrained`?

They should and they are in the main package. There are additional outputs in the recipe for client and server, which have the corresponding dependencies set.

**Comment by ifitchet** [comment]
> They should and they are in the main package.

Right.  I'm being discombobulated by the GH diff preview.

**Review by ifitchet — APPROVED** [review]
LGTM

**Pull request merged**
